### ISSUE TITLE
Create GitHub Workflow for Tagged Releases and Packaging

### ISSUE THREAD

**Issue by obi-wan-shinobi** [remla25-team15/lib-version#3]
### Description:

We need to automate our release process via GitHub Actions to ensure versioning and packaging are handled cleanly from the main branch.

Our project should use a `version.txt` file to store the current version number. This file is read by `setup.py` to determine the package version.

For e.g. setup.py can contain something like:
```python3
with open("version.txt") as f:
    version = f.read().strip()
```

The idea then is that devs will create tags like `vX.Y.Z-release` to indicate that this should be the next release.
Then the GitHub action will pick this up and correctly update the `version.txt` file to ensure that the actual release tag 
has the correct version in `version.txt`.

### Task
Create a GitHub Actions workflow that automates the release process based on specially formatted tags.

#### Workflow Requirements
1. **Trigger**: On tags created on the `main` branch, matching the pattern `vX.Y.Z-release`  
   _(e.g., `v1.2.3-release`)_

2. **Job 1 – Update Version File**:
   - Parse the tag to extract the version (e.g., `v1.2.3`)
   - Write that version into `version.txt`
   - Commit and push this change back to `main`

3. **Job 2 – Tag Final Release**:
   - Create a new Git tag using just the version (e.g., `v1.2.3`)
   - Push this tag to GitHub

This will then trigger our current workflow which uploads artifacts as before.

The current workflow only uploads artifacts when we create a tag but we should also make official releases like currently being done in `app-service`.

The job in `app-service`: https://github.com/remla25-team15/app-service/blob/update-release-job/.github/workflows/build-and-push.yml
looks something like this:

```
 create-release:
    runs-on: ubuntu-24.04
    needs: build-and-push
    permissions:
      contents: write
    steps:
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.REMLA_GITHUB_TOKEN }}
```

We should add a similar job to this repository to make GitHub releases. I think the rest of the workflow stays the same.
